---
version: "3.8"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/Chicago
      - UMASK_SET=022
      - VERSION=docker
    volumes:
      - /data/configs/plex:/config
      - /data/media/tv:/tv
      - /data/media/movies:/movies
    restart: unless-stopped

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=2001
      - PGID=2000
      - TZ=America/Chicago
    volumes:
      - /data/configs/sabnzbd:/config
      - /data:/data
    ports:
      - 8080:8080
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=2002
      - PGID=2000
      - TZ=America/Chicago
    volumes:
      - /data/configs/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=2003
      - PGID=2000
      - TZ=America/Chicago
    volumes:
      - /data/configs/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
